mysite/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()
#這個views指的是mysite/mysite/views.py
from views import here, math, welcome, iron_man
#資料夾不同，from之位置亦不同
#list_restaurants為顯示餐廳列表模版
from restaurants.views import menu,list_restaurants, comment



urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^here/$', here),
    url(r'^(\d{1,2})/math/(\d{1,2})/$', math),
    url(r'^menu/$', menu),
    url(r'^welcome/$', welcome),
    url(r'^restaurants_list/$', list_restaurants),
    #提供一個參數:餐廳id，以顯示對應的餐廳評價
    url(r'^comment/(\d{1,5})/$', comment),
    #不輸入任何頁面名稱
    url(r'^$',iron_man)
)

restaurants/models.py
#!/usr/bin/env python
# encoding: utf-8

#所有模型繼承自django.db.models.Model類別
from django.db import models


class Restaurant(models.Model):
    name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=15)
    address = models.CharField(max_length=50, blank=True)

    def __unicode__(self):
        """
        :returns: name string

        """
        return self.name


class Food(models.Model):
    #max_length限制資料長度
    name = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=3, decimal_places=0)
    #blank 表示允許資料留空
    comment = models.CharField(max_length=50, blank=True)
    is_spicy = models.BooleanField(default=False)
    #資料表關聯性的概念
    #表示多種食物對應到一家餐聽的概念(Many-to-one)
    restaurant = models.ForeignKey(Restaurant)

    def __unicode__(self):
        """
        :returns: name string

        """
        return self.name

    class Meta:

        """Meta: attribute, options"""

        ordering = ['price']

class Comment(models.Model):
    content = models.CharField(max_length=255)
    visitor = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    date_time = models.DateTimeField()
    restaurant = models.ForeignKey(Restaurant)

restaurants/forms.py
# encoding: utf-8
#表單模型化
from django import forms

class CommentForm(forms.Form):
    visitor = forms.CharField(max_length = 20)
    email = forms.EmailField(max_length = 20, required = False) #required = False表示並非必填
    content = forms.CharField(max_length = 200, widget = forms.Textarea())
    
    #自定義驗證規則
    def clean_content(self):
    	content = self.cleaned_data['content']
    	if len(content) < 5:
    		raise forms.ValidationError('字數不足')
    	return content

mysite/views.py
# encoding: utf-8

from django.http import HttpResponse
from django.shortcuts import render_to_response


def here(request):
    return HttpResponse('媽，我在這!')


def math(request, a, b):
    a = int(a)
    b = int(b)
    s = a + b
    d = a - b
    p = a * b
    q = a / b
    return render_to_response('math.html', {'s': s, 'd': d, 'p': p, 'q': q})

def welcome(request):
    if 'user_name' in request.GET and request.GET['user_name'] != '':
        return HttpResponse('Welcome!~'+request.GET['user_name'])
    else:
        return render_to_response('welcome.html', locals())

def iron_man(request):
    return render_to_response('iron_man.html',locals())

restaurants/views.py
#!/usr/bin/env python
# encoding: utf-8
#重新導入pattern函數用
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from restaurants.models import Restaurant, Comment
#date_time用的
from django.utils import timezone
from django.template import RequestContext
from restaurants.forms import CommentForm

def menu(request):
    """retrun a menu response

    :request: client request
    :returns: http response

    """
    path = request.path
    #先檢查request.GET有沒有id，若有則以get方法取得對應餐廳
    if 'id' in request.GET and request.GET['id'] != '':
    	restaurant = Restaurant.objects.get(id=request.GET['id'])
        return render_to_response('menu.html', locals())
    #若沒有則會讓頁面重導至pattern:/restaurants_list/
    else:
        return HttpResponseRedirect("/restaurants_list/")


def list_restaurants(request):
	restaurants = Restaurant.objects.all()
	return render_to_response('restaurants_list.html', locals())

def comment(request, restaurant_id):
    if restaurant_id:
        r = Restaurant.objects.get(id=restaurant_id)
    else:
        return HttpResponseRedirect("/restaurants_list/")
    errors = [] #用於作欄位正確性判斷
    if request.POST:
        f = CommentForm(request.POST)
        if f.is_valid():
            visitor = f.cleaned_data['visitor']
            content = f.cleaned_data['content']
            email = f.cleaned_data['email']
            date_time = timezone.localtime(timezone.now())
            c = Comment.objects.create(
                visitor=visitor, email=email,
                content=content,
                date_time=date_time,
                restaurant=r
            )
            #產生一個非綁定表單，將生成html碼
            #設定初始值
            f = CommentForm(initial={'content':'我沒意見'})
    else:
        f = CommentForm(initial={'content':'我沒意見'})
    return render_to_response('comments.html', RequestContext(request,locals()))

restaurants/templates/comments.html
<!doctype html>
<html>
    <head>
        <title> Comment </title>
        <meta charset='utf-8'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
        <style>
        th { text-align: center; }
        div.center_padding {
            text-align: center;
            padding: 128px 15px;
        }
        .errorlist {
            color: red;
        }
        </style>
    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">MySite</a>
                </div>
                <!--div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                </div--><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container">
            <div class="center_padding">
                <h2>{{ r.name }}的評價</h2>
                {% if r.comment_set.all %}
                <p>目前共有{{ r.comment_set.all|length }}條評價</p>
                <table class="table table-hover">
                    <tr>
                        <th>留言者</th>
                        <th>時間</th>
                        <th>評價</th>
                    </tr>
                    {% for c in r.comment_set.all %}
                    <tr>
                        <td> {{ c.visitor }} </td>
                        <td> {{ c.date_time | date:"F j, Y" }} </td>
                        <td> {{ c.content }} </td>
                    </tr>
                    {% endfor %}
                </table>
                {% else %}
                <p>無評價</p>
                {% endif %}

                <br /><br />
                {% if f.errors %}
                <p style="color:red;">
                    請依提示修復表單錯誤
                </p>
                {% endif %}

                <form action="" method="post" class="form-horizontal" role="form" style="width:33%; margin:auto; text-align:left">{% csrf_token %}
                    <div class="form-group">
                    <label for="visitor">留言者:</label>
                    {{ f.visitor }}
                    {{ f.visitor.errors }}
                    </div>
                    <div class="form-group">
                        <label for="email">電子信箱:</label>
                    {{ f.email }}
                    {{ f.email.errors }}
                    </div>
                    <div class="form-group">
                    <label for="content">評價:</label>
                    {{ f.content }}
                    {{ f.content.errors }}
                    </div>
                    <input type="submit" value="給予評價" class="btn btn-default">
                </form>
            </div>
        </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    </body>
</html>

restaurants/templates/menu.html
<!doctype html>
<html>
    <head>
        <title> Menu </title>
        <meta charset='utf-8'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
        <style>
        th { text-align: center; }
        div.center_padding {
            text-align: center;
            padding: 128px 15px;
        }
        </style>
    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">MySite</a>
                </div>
            </div>
        </nav>

        <div class="container">
            <div class="center_padding">
                <h2>{{ restaurant.name }}的Menu</h2>
                {% if restaurant.food_set.all %}
                <p>本餐廳共有{{ restaurant.food_set.all|length }}道菜</p>
                <table class="table table-hover">
                    <tr>
                        <th>菜名</th>
                        <th>價格</th>
                        <th>註解</th>
                        <th>辣不辣</th>
                    </tr>
                    {% for food in restaurant.food_set.all %}
                    <tr>
                        <td> {{ food.name }} </td>
                        <td> {{ food.price }} </td>
                        <td> {{ food.comment }} </td>
                        <td> {% if food.is_spicy %} 辣 {% else %} 不辣 {% endif %} </td>
                    </tr>
                    {% endfor %}
                </table>
                {% else %}
                <p>本餐廳啥都沒賣</p>
                {% endif %}

            </div>
        </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    </body>
</html>

restaurants/templates/restaurants_list.html
<!doctype html>
<html>
    <head>
        <title> Restaurants </title>
        <meta charset='utf-8'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
        <style>
        th { text-align: center; }
        div.center_padding {
            text-align: center;
            padding: 128px 15px;
        }
        </style>
    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">MySite</a>
                </div>
            </div>
        </nav>

        <div class="container">
            <div class="center_padding">
                <h2>餐廳列表</h2>
                <form action="/menu/" method="get">
                <table class="table table-hover">
                    <tr>
                        <th>選取</th>
                        <th>店名</th>
                        <th>電話</th>
                        <th>地址</th>
                        <th>評價</th>
                    </tr>
                    {% for r in restaurants %}
                    <tr>
                         <td> <input type="radio" name="id" value="{{r.id}}"> </td>
                        <td> {{ r.name }} </td>
                        <td> {{ r.phone_number }} </td>
                        <td> {{ r.address }} </td>
                        <td> <a href="/comment/{{r.id}}/"> 評價 </a> </td> 
                    </tr>
                    {% endfor %}
                </table>
                <input type="submit" value="觀看menu" class="btn btn-default">
                </form>
            </div>
        </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    </body>
</html>

templates/contact.html
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
               <h2>Contact Eggsy Chen</h2>
                <p>Feel free to email me to provide some feedback</p>
                <p>歡迎交流分享</p>
                <p><a href="mailto:gn00533502@gmail.com">gn00533502@gmail.com</a>
                </p>
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://www.facebook.com/boss.chen.543" class="btn btn-default btn-lg"><i class="fa fa-facebook"></i> <span class="network-name">Facebook</span></a>
                    </li>
                    <li>
                        <a href="https://github.com/gn00533502" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                    </li>
                    <li>
                        <a href="https://plus.google.com/u/0/103971470423905558967/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                    </li>
                </ul>
            </div>
        </div>

templates/intro.html
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About IRONMAN</h2>
                <p>Iron Man (Tony Stark) is a fictional superhero appearing in American comic books published by Marvel Comics, as well as its associated media. The character was created by writer and editor Stan Lee, developed by scripter Larry Lieber, and designed by artists Don Heck and Jack Kirby. He made his first appearance in Tales of Suspense</p>
                <!-- <p>This theme features stock photos by <a href="http://gratisography.com/">Gratisography</a> along with a custom Google Maps skin courtesy of <a href="http://snazzymaps.com/">Snazzy Maps</a>.</p> -->
                <p>An American billionaire playboy, business magnate, and ingenious engineer, Tony Stark suffers a severe chest injury during a kidnapping in which his captors attempt to force him to build a weapon of mass destruction. He instead creates a powered suit of armor to save his life and escape captivity. Later, Stark augments his suit with weapons and other technological devices he designed through his company, Stark Industries. He uses the suit and successive versions to protect the world as Iron Man, while at first concealing his true identity. Initially, Iron Man was a vehicle for Stan Lee to explore Cold War themes, particularly the role of American technology and business in the fight against communism.Subsequent re-imaginings of Iron Man have transitioned from Cold War themes to contemporary concerns, such as corporate crime and terrorism.</p>
            </div>
        </div>

templates/iron_man.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <link rel="shortcut icon" href="{% static "favicon.ico" %}">
    <link rel="Bookmark" href="{% static "favicon.ico" %}">

    <meta charset="big5">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>IRON MAN</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/grayscale.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <i class="fa fa-play-circle"></i>  <span class="light">Home</span> Iron Man
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">IRONMAN INTRO</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#download">official(ironman3)</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#news">Latest news</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#portfolio">wallpaper</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#me">ABOUT ME</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">IRON MAN</h1>
                        <iframe width="300" height="200" src="https://www.youtube.com/embed/VVyoXimCrdQ?rel=0&amp;controls=0&amp;showinfo=0 &autoplay=1" frameborder="0" allowfullscreen></iframe>
                        <font color="orange"><p class="intro-text">Genius, billionaire, playboy, philanthropist.<br>I AM </font><font color="red">IRON MAN</font></p>
                        <!-- 一個可捲到about的按鈕 -->
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
    {% include 'intro.html' %}
    </section>

    <!-- Official Section -->
    <section id="download" class="content-section text-center">
    {% include 'official.html' %}
    </section>

    <!-- Latest news Section  -->
    <section id="news" class="container content-section text-center">
    {% include 'news.html' %}
    </section>

    <!-- Portfolio Grid Section -->
    <section id="portfolio">
    {% include 'wallpaper.html' %}
    </section>


    <!-- me Section -->
    <section id="me" class="content-section text-center">
    {% include 'me.html' %}
    </section>

    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
    {% include 'contact.html' %}
    </section>

    <!-- Map Section -->
    <div id="map"></div>

    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>公司位置</p>
            <p>Copyright &copy; Your Website 2014</p>
        </div>
    </footer>


    <!-- jQuery -->
    <script src="{% static "js/jquery.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static "js/jquery.easing.min.js" %}"></script>

    <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCMrN75OBOz7O114oR4cHGsezh9T2Y51b4&callback=initMap"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static "js/grayscale.js" %}"></script>

</body>

</html>

templates/math.html
<html>
    sum={{s}}<br>
    dif={{d}}<br>
    pro={{p}}<br>
    quo={{q}}
</html>

templates/me.html
{% load staticfiles %}
        <div class="row">
            <div class="col-md-3 col-md-offset-3">
                <img src="{% static 'img/IMG_1732.jpg' %}" class="img-responsive" alt="Responsive image">
            </div>
            <div class="col-md-3">
                <h2>關於我</h2>
                <p>各位好，我是伊格西</p><br>
                <p>我只是一個小小的鋼鐵人粉絲</p><br>
                <p>分享一下自己熱愛鋼鐵人的網頁~</p>
            </div>
        </div> 

templates/news.html
       <div class="row">
            <div class="col-md-6">
                The Past is Prelude - Marvel's Captain America: Civil War
                <iframe width="300" height="200" src="https://www.youtube.com/embed/6Fc-qgLGQ-I?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>  
            </div>
            <div class="col-md-6">
                Brothers in Arms - Marvel's Captain America: Civil War Featurette
                <iframe width="300" height="200" src="https://www.youtube.com/embed/8K5QY8X91vI?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                 【美國隊長3: 英雄內戰】HD最終版中文電影預告<br>
                 <iframe width="300" height="200" src="https://www.youtube.com/embed/6Mwwl5iAWDQ?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>

templates/official.html
        <div class="download-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <br><br><br><br><br><br>
                    <!-- <font color="orange"><h2>鋼鋼</h2></font> -->
                    <a href="http://marvel.com/movies/movie/176/iron_man_3" class="btn btn-default btn-lg">Visit official Page</a>
                </div>
            </div>
        </div>

templates/welcome.html
<!doctype html>
<html>
    <head>
        <title> Welcome </title>
        <meta charset='utf-8'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
        <style>
        th { text-align: center; }
        div.center_padding {
            text-align: center;
            padding: 128px 15px;
        }
        </style>
    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">MySite</a>
                </div>
            </div>
        </nav>

        <div class="container">
            <div class="center_padding">
                <form action="" method="get" class="form-inline">
                    <label for="user_name">您的名字</label>
                    <input id="user_name" type="text" name="user_name" class="form-control" placeholder="例如：台灣人">
                    <input type="submit" value="進入網站" class="btn btn-default">
            </div>
        </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    </body>
</html>